# ----
# Site

title: Open Source Timer
description: A universal open source timer
url: https://example.com
google_analytics_key:
permalink: pretty

collections:
  overview:
    title: Overview
    position: 1
  tdl:
    title: Timer Description Language
    position: 2
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post
